query GetPokedexEntries($version_group_id: Int) {
    pokemon_v2_pokedex(
        where: {pokemon_v2_pokedexversiongroups: {version_group_id: {_eq: $version_group_id}}}
    ) {
        name
        pokemon_v2_pokemondexnumbers(
            order_by: {pokedex_number: asc}
        ) {
            pokedex_number
            pokemon_v2_pokemonspecy {
                name
                id
                pokemon_v2_pokemons(
                    where: {is_default: {_eq: true}}
                ) {
                    pokemon_v2_pokemontypes {
                        pokemon_v2_type {
                            id
                            name
                        }
                    }
                }
            }
        }
    }
}
